steps:
  # # Clone the repository
  # - name: 'gcr.io/cloud-builders/git'
  #   args: ['clone', 'https://github.com/saurabhmi2212/spring-petclinic.git']
  #   dir: 'workspace'
    
  # # Build the Docker image of the microservice
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['build', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/petclinic-app-repo/petclinic:$SHORT_SHA', './workspace/spring-petclinic']
  
  # # Push the Docker image to the container registry
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/petclinic-app-repo/petclinic:$SHORT_SHA']  

  # Set up kubectl
  - name: gcr.io/cloud-builders/kubectl
    id: Configure kubectl
    args:
      - cluster-info
    env:
      - 'PROJECT=halogen-byte-388404'
      - 'CLOUDSDK_COMPUTE_REGION=asia-south1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=petclinic-cluster'
      - KUBECONFIG=/workspace/.kube/config

  # Set up Helm and deploy the application
    # This step generates the new manifest
  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy 
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
         curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | tee /usr/share/keyrings/helm.gpg > /dev/null
         apt-get install apt-transport-https --yes
         echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | tee /etc/apt/sources.list.d/helm-stable-debian.list
         apt-get update
         apt-get install helm
         helm upgrade --install petclinic ./deployment-chart/petclinic-chart --namespace=petclinic --wait
     env:
      - 'HELM_HOME=/workspace/'
      - 'KUBECONFIG=/workspace/.kube/config'
      - 'CLOUDSDK_COMPUTE_ZONE=asia-south1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=petclinic-cluster'
