steps:
  # Clone the repository
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/saurabhmi2212/spring-petclinic.git']
    dir: 'workspace'

  # # Step to build the Java JAR file
  # - name: 'gcr.io/cloud-builders/mvn'
  #   args: ['package']
  #   # args: ['clean', 'install']
  #   dir: 'petclinic/spring-petclinic'

  # # Check code quality with Checkstyle
  # - name: 'gcr.io/cloud-builders/mvn'
  #   args: ['checkstyle:checkstyle']
  #   dir: 'workspace/petclinic/spring-petclinic'
    
  # Build the Docker image of the microservice
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/halogen-byte-388404/petclinic-app-repo/petclinic:$COMMIT_SHA', './workspace/spring-petclinic']
  
  # # Push the Docker image to the container registry
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['push', 'asia-south1-docker.pkg.dev/halogen-byte-388404/petclinic-app-repo/petclinic:$COMMIT_SHA']      
